### ISSUE TITLE
Add quich search feature on each page of Каталог сервисов

### ISSUE THREAD

**Issue by VVist** [iboxdev/online#27]
Необходимо реализовать наличие функции выбрать регион и наличия строки быстрого поиска на всех страницах раздела каталог сервисов. Такая возможность удачно реализована https://24money.com.ua/communication (в строке поиска можно вводить только провайдера представленном в разделе)  https://easypay.ua/internet-tv  (Только строка поиска. в строке поиска можно вводить только провайдера представленном в разделе)  https://www.ipay.ua/ru/bills/internet (с троке поиска будет найдена любая компания не зависимо от раздела, где находиться клиент)

**Comment by MBatsmanov** [comment]
Не актуально. От "живого поиска" и выбора региона решено отказаться. Строку выбора региона необходимо убрать.
